### ISSUE TITLE
TMXTiledMapのscaleを変更していた場合、FixtureDefが正常に生成されない

### ISSUE THREAD

**Issue by yusan25c** [raharu0425/TileBodyCreator#1]
initCollisionMapパラメータmapのscale設定を変更した場合が考慮されていないようです。
createRect等にscaleを渡してやるとうまく生成されます。
ご確認をお願いいたします。

**Comment by yuzoh** [comment]
修正を行いPullRequestを行わせていただきました。
https://github.com/raharu0425/TileBodyCreator/pull/2

ご確認をお願いいたします。
